# .github/workflows/docs.yml

name: Build & Deploy Sphinx Docs

on:
  push:
    branches: [main]

permissions:
  contents: write 

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install
          poetry run pip install -r docs/requirements.txt
          eval $(poetry env activate)

      - name: Build Sphinx docs
        run: |
          eval $(poetry env activate)
          make -C docs clean
          make -C docs html
          ls 

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
      #     destination_dir: latest
