# .github/workflows/docs.yml

name: Build & Deploy Sphinx Docs

on:
  push:
    branches: [main]

permissions:
  contents: write 

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Download and install Pandoc 3.7.0.2
        run: |
          VERSION=3.7.0.2
          FILE="pandoc-${VERSION}-1-amd64.deb"
          URL="https://github.com/jgm/pandoc/releases/download/${VERSION}/${FILE}"

          echo "Downloading $FILE..."
          curl -L -o pandoc.deb "$URL"

          echo "Installing Pandoc..."
          sudo dpkg -i pandoc.deb

      - name: Verify Pandoc version
        run: pandoc --version

      - name: Install dependencies
        run: |
          poetry lock
          poetry install --with docs
          eval $(poetry env activate)

      - name: Build Sphinx docs
        run: |
          eval $(poetry env activate)
          make -C docs clean
          make -C docs html
          tree 

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          destination_dir: latest
          keep_files: true
