name: Linting with Ruff

on:
    push:
        branches:
        - main
        - develop
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    ruff-formatting:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.9"
            cache: 'pip'
        - name: Install Ruff
          run: pip install ruff==0.9.7
        - name: Lint with Ruff
          run: |
            ruff check uqlm/
